### ISSUE TITLE
[Bug] Registration error in deployed application

### ISSUE THREAD

**Issue by olivierobert** [nainglinaung/scaper-dashboard#2]
## Issue

Upon trying out the deployed application, I could not register for an account.

STR:
1. Go to http://35.188.64.46/register
2. Fill in the form
3. Click on the button "register"

> [!NOTE]
> The issue seems to stem from a configuration issue as the frontend application is sending a request to a local environment
> <img width="989" alt="Screenshot 2566-11-07 at 15 03 10" src="https://github.com/nainglinaung/scaper-dashboard/assets/696529/c05b5453-749a-42e0-8683-519ac0f84eb1">

**Comment by nainglinaung** [comment]
Thank you for bringing this to my attention. As you mentioned, the problem was related to a configuration issue. I overlooked allowing the port in Google Cloud Platform (GCP). It should be resolved now.

**Comment by olivierobert** [comment]
Still facing the issue when going to http://35.188.64.46/register

<img width="1007" alt="image" src="https://github.com/nainglinaung/scaper-dashboard/assets/696529/88206f73-bf11-404a-b775-d209f5701630">

**Comment by nainglinaung** [comment]
The next problem appears to be related to the HTTPS certificate. If you encounter this issue, please consider making temporary adjustments to your settings in Chrome. I believe there are similar methods for addressing this in Firefox as well.

https://stackoverflow.com/questions/66534759/cors-error-on-request-to-localhost-dev-server-from-remote-site

**Comment by olivierobert** [comment]
Such a solution would be impractical for a real-world application as this would need to be resolved on the infrastructure side of the application. For now, I will be reviewing the application in my local environment.
